### ISSUE TITLE
Please add multiplayer

### ISSUE THREAD

**Issue by pavi2410** [PoseidonCoder/tertle#1]
https://boardgame.io might be helpful

**Comment by PoseidonCoder** [comment]
![image](https://user-images.githubusercontent.com/34260118/163914012-3901cf3b-4417-4203-bdc2-d4324f8cfa94.png)
Done! It still needs a little work, but I'm quite happy with how it turned out. I didn't go down the boardgame.io route because it was only for turn-based gameplay. Instead, I just set up a simple socket.io server on Heroku. Right now all the games are just stored in a variable, but I might change that soon. Thanks for the idea!

**Comment by pavi2410** [comment]
Good job @PoseidonCoder 

This feature will come handy when I play with my friends in class 😂
